name: Build Alchemy APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar Codigo
        uses: actions/checkout@v4

      - name: 2. Configurar Java (Version 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 3. Configurar Flutter (Version 2026)
        uses: subosito/flutter-action@v2
        with:
          # Buscamos la mas nueva para que coincida con tu Dart 3.8+
          flutter-version: 'any' 
          channel: 'stable'
          cache: true

      - name: 4. Limpieza y Construccion de APK
        run: |
          # Aceptamos licencias de Google Android (Evita el Error 255)
          yes | sdkmanager --licenses || true
          
          # Borramos rastro de carpetas locales antiguas
          rm -f pubspec.lock
          flutter clean
          
          # Descargamos las librerías de internet (las que ya no tienen "path")
          flutter pub get
          
          # LIMPIEZA CLAVE DE GRADLE (Para quitar el Error 255)
          cd android && ./gradlew clean && cd ..
          
          # CONSTRUCCION FINAL DEL APK
          # Usamos --no-tree-shake-icons por si alguna libreria de iconos falla
          flutter build apk --release --no-tree-shake-icons

      - name: 5. Guardar y Descargar APK
        uses: actions/upload-artifact@v4
        with:
          name: Alchemy-Instalador-APK
          path: build/app/outputs/flutter-apk/app-release.apk
