name: Build Alchemy APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar Codigo
        uses: actions/checkout@v4

      - name: 2. Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 3. Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'any' 
          channel: 'stable'

      - name: 4. Construccion del APK
        run: |
          # Borramos rastros de intentos anteriores
          rm -f pubspec.lock
          flutter clean
          
          # Descargamos las librerías (Con el https:// ahora funcionará)
          flutter pub get
          
          # Generamos el instalador
          flutter build apk --release --no-tree-shake-icons

      - name: 5. Descargar APK
        uses: actions/upload-artifact@v4
        with:
          name: Alchemy-Instalador-APK
          path: build/app/outputs/flutter-apk/app-release.apk
